### ISSUE TITLE
Error on downloading playlist

### ISSUE THREAD

**Issue by lal12** [AllToMP3/alltomp3#3]
I tried to download a playlist (https://www.youtube.com/playlist?list=PLa9c_3U5StsLdALdu6YlxRfmryQGC-sAW) but after one file is downloaded I get the following error: 

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn fpcalc ENOENT
    at exports._errnoException (util.js:896:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

This is my code:

```
const alltomp3 = require("alltomp3");

alltomp3.downloadPlaylistWithURLs('https://www.youtube.com/playlist?list=PLa9c_3U5StsLdALdu6YlxRfmryQGC-sAW', '.', function(a,b){
    console.log(a,b);
}, 10);
```

**Comment by NTag** [comment]
Did you install the requirements?

Can you do:
```
ffmpeg -v
fpcalc -v
eyeD3 --version
```
?
