### ISSUE TITLE
not giving tags to downloaded file after download

### ISSUE THREAD

**Issue by NicolaiVdS** [AllToMP3/alltomp3#7]
Hi i get folowing error when i try to run the example code 
`Uncaught Exception:
Error: spawn fpcalc ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

when i look into the folder the mp3 is there but not with the tags

**Comment by NicolaiVdS** [comment]
fixed issue was with fpcalc not correctly installed
